export const mapa2=[
    {
        posicion:0,
        direccion:"0000",
        contenido:1
    },
    {
      posicion:1,
      direccion:"0001",
      contenido:1
    },
    {
      posicion:2,
      direccion:"0002",
      contenido:1
    },
    {
      posicion:3,
      direccion:"0003",
      contenido:1
    },
    {
      posicion:4,
      direccion:"0004",
      contenido:1
    },
    {
      posicion:5,
      direccion:"0005",
      contenido:1
    },
    {
      posicion:6,
      direccion:"0006",
      contenido:1
    },
    {
      posicion:7,
      direccion:"0007",
      contenido:1
    },
    {
      posicion:8,
      direccion:"0008",
      contenido:1
    },
    {
      posicion:9,
      direccion:"0009",
      contenido:1
    },
    {
      posicion:10,
      direccion:"000A",
      contenido:1
    },
    {
      posicion:11,
      direccion:"000B",
      contenido:1
    },
    {
      posicion:12,
      direccion:"000C",
      contenido:1
    },
    {
      posicion:13,
      direccion:"000D",
      contenido:1
    },
    {
      posicion:14,
      direccion:"000E",
      contenido:1
    },
    {
      posicion:15,
      direccion:"000F",
      contenido:1
    },
    {
      posicion:16,
      direccion:"0010",
      contenido:1
    },
    {
      posicion:17,
      direccion:"0011",
      contenido:1
    },
    {
      posicion:18,
      direccion:"0012",
      contenido:1
    },
    {
      posicion:19,
      direccion:"0013",
      contenido:1
    },
    {
      posicion:20,
        direccion:"0014",
        contenido:1
      },
      {
        posicion:21,
        direccion:"0015",
        contenido:1
      },
      {
        posicion:22,
        direccion:"0016",
        contenido:1
      },
      {
        posicion:23,
        direccion:"0017",
        contenido:1
      },
      {
        posicion:24,
        direccion:"0018",
        contenido:1
      },
      {
        posicion:25,
        direccion:"0019",
        contenido:1
      },
      {
        posicion:26,
        direccion:"001A",
        contenido:1
      },
      {
        posicion:27,
        direccion:"001B",
        contenido:1
      },
      {
        posicion:28,
        direccion:"001C",
        contenido:1
      },
      {
        posicion:29,
        direccion:"001D",
        contenido:1
      },
      {
        posicion:30,
        direccion:"001E",
        contenido:1
      },
    {
      posicion:31,
      direccion:"001F",
      contenido:1
    },
    
    
    
];